"""create prime numbers table

Revision ID: bee5e2b7420f
Revises: 
Create Date: 2025-12-26 12:17:56.959955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee5e2b7420f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prime_number_requests',
    sa.Column('request_id', sa.String(length=255), nullable=False),
    sa.Column('no_of_primes', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'FINISHED', 'FAILED', name='prime_number_request_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('celery_req_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_prime_number_requests_request_id'), 'prime_number_requests', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prime_number_requests_request_id'), table_name='prime_number_requests')
    op.drop_table('prime_number_requests')
    # ### end Alembic commands ###
